// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNbiTVqInIqBhkjCwAFL6llxdaocYIsI',
    appId: '1:737877842262:web:164f2088bee0155ae1def7',
    messagingSenderId: '737877842262',
    projectId: 'moduchef-project',
    authDomain: 'moduchef-project.firebaseapp.com',
    storageBucket: 'moduchef-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrl5TnlwNjQoG4GqVIx1Pmrb8a2-NjwM0',
    appId: '1:737877842262:android:632646a3c96c2ff5e1def7',
    messagingSenderId: '737877842262',
    projectId: 'moduchef-project',
    storageBucket: 'moduchef-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQrlaUpmEt12KHYplj0_NjMrTaxhbutY',
    appId: '1:737877842262:ios:66d9c0da41ae9295e1def7',
    messagingSenderId: '737877842262',
    projectId: 'moduchef-project',
    storageBucket: 'moduchef-project.appspot.com',
    iosBundleId: 'com.example.fridgeat',
  );
}
